'use strict';

module.exports = {
// definitions from linux/fb.h
  FBIOGET_VSCREENINFO: 0x4600,
  FBIOGET_FSCREENINFO: 0x4602,
  FBIOBLANK: 0x4611,
  FB_TYPE_PACKED_PIXELS: 0,
  FB_TYPE_PLANES: 1,
  FB_TYPE_INTERLEAVED_PLANES: 2,
  FB_TYPE_TEXT: 3,
  FB_TYPE_VGA_PLANES: 4,
  FB_TYPE_FOURCC: 5,
  FB_VISUAL_MONO01: 0,
  FB_VISUAL_MONO10: 1,
  FB_VISUAL_TRUECOLOR: 2,
  FB_VISUAL_PSEUDOCOLOR: 3,
  FB_VISUAL_DIRECTCOLOR: 4,
  FB_VISUAL_STATIC_PSEUDOCOLOR: 5,
  FB_VISUAL_FOURCC: 6,
  FB_BLANK_UNBLANK: 0,
  FB_BLANK_POWERDOWN: 4
};
